vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_profiles:
            uri_prefix: /images/user-profiles
            upload_destination: '%kernel.project_dir%/public/images/user-profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
